system:
  device_name: "RaspberryPi_Unit_1"
  version: "1.2.0"
  
camera:
  index: 0
  width: 1280
  height: 720

model:
  # ‚ö†Ô∏è 1. ‡πÅ‡∏Å‡πâ base_path ‡πÄ‡∏õ‡πá‡∏ô "models" ‡πÄ‡∏â‡∏¢‡πÜ (‡πÄ‡∏û‡∏£‡∏≤‡∏∞‡∏Ç‡πâ‡∏≤‡∏á‡πÉ‡∏ô‡πÄ‡∏£‡∏≤‡πÅ‡∏ö‡πà‡∏á folder pill/box ‡πÅ‡∏•‡πâ‡∏ß)
  base_path: "models"

  # üì¶ 1. ‡∏£‡∏∞‡∏ö‡∏ö‡∏´‡∏≤‡∏Å‡∏•‡πà‡∏≠‡∏á (YOLO)
  box_detector:
    enabled: true
    onnx: "box_detector.onnx"   # (‡∏≠‡∏±‡∏ô‡∏ô‡∏µ‡πâ‡πÄ‡∏ä‡πá‡∏Ñ‡∏î‡πâ‡∏ß‡∏¢‡∏ô‡∏∞‡∏Ñ‡∏£‡∏±‡∏ö‡∏ß‡πà‡∏≤‡∏°‡∏µ‡πÑ‡∏ü‡∏•‡πå‡∏ô‡∏µ‡πâ‡πÉ‡∏ô models/ ‡∏´‡∏£‡∏∑‡∏≠‡∏¢‡∏±‡∏á)
    
    # ‚ö†Ô∏è 2. ‡πÅ‡∏Å‡πâ path ‡πÉ‡∏´‡πâ‡∏ä‡∏µ‡πâ‡πÑ‡∏õ‡∏ó‡∏µ‡πà‡∏ï‡∏±‡∏ß‡πÉ‡∏´‡∏°‡πà
    weights: "box/best_model.pth" 
    
    img_size: 640
    conf_threshold: 0.50

  # üè∑Ô∏è 2. ‡∏£‡∏∞‡∏ö‡∏ö‡∏≠‡πà‡∏≤‡∏ô‡∏ä‡∏∑‡πà‡∏≠‡∏Å‡∏•‡πà‡∏≠‡∏á (ArcFace)
  box_classifier:
    img_size: 384
    conf_threshold: 0.9

  # üíä 3. ‡∏£‡∏∞‡∏ö‡∏ö‡∏´‡∏≤‡πÄ‡∏°‡πá‡∏î‡∏¢‡∏≤ (YOLO)
  pill_detector:
    enabled: true
    onnx: "pill_detector.onnx"  # (‡πÄ‡∏ä‡πá‡∏Ñ‡∏î‡πâ‡∏ß‡∏¢‡∏ô‡∏∞‡∏Ñ‡∏£‡∏±‡∏ö‡∏ß‡πà‡∏≤‡∏°‡∏µ‡πÑ‡∏ü‡∏•‡πå‡∏ô‡∏µ‡πâ‡πÑ‡∏´‡∏°)
    conf_threshold: 0.6

  # üß™ 4. ‡∏£‡∏∞‡∏ö‡∏ö‡∏≠‡πà‡∏≤‡∏ô‡∏ä‡∏∑‡πà‡∏≠‡∏¢‡∏≤ (ArcFace)
  pill_classifier:
    enabled: true
    
    # ‚ö†Ô∏è 3. ‡πÅ‡∏Å‡πâ path ‡πÉ‡∏´‡πâ‡∏ä‡∏µ‡πâ‡πÑ‡∏õ‡∏ó‡∏µ‡πà‡∏ï‡∏±‡∏ß‡πÉ‡∏´‡∏°‡πà
    weights: "pill/best_model.pth"
    
    img_size: 384
    conf_threshold: 0.9
