system:
  device_name: "RaspberryPi_Unit_1"
  version: "1.2.0"
  
camera:
  index: 0
  width: 1280
  height: 720

model:
  base_path: "models/active"

  # üì¶ 1. ‡∏£‡∏∞‡∏ö‡∏ö‡∏´‡∏≤‡∏Å‡∏•‡πà‡∏≠‡∏á (YOLO)
  box_detector:
    enabled: true
    onnx: "box_detector.onnx"
    weights: "box_model_production.pth" # ‡πÉ‡∏ä‡πâ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö Classifier
    img_size: 640
    conf_threshold: 0.50  # ‡∏Ñ‡∏ß‡∏≤‡∏°‡∏°‡∏±‡πà‡∏ô‡πÉ‡∏à‡∏ß‡πà‡∏≤ "‡πÄ‡∏à‡∏≠‡∏Å‡∏•‡πà‡∏≠‡∏á" (YOLO)

  # üè∑Ô∏è 2. ‡∏£‡∏∞‡∏ö‡∏ö‡∏≠‡πà‡∏≤‡∏ô‡∏ä‡∏∑‡πà‡∏≠‡∏Å‡∏•‡πà‡∏≠‡∏á (ArcFace)
  box_classifier:
    img_size: 384
    conf_threshold: 0.9  # ‡∏Ñ‡∏ß‡∏≤‡∏°‡∏°‡∏±‡πà‡∏ô‡πÉ‡∏à‡∏ß‡πà‡∏≤ "‡πÄ‡∏õ‡πá‡∏ô‡∏Å‡∏•‡πà‡∏≠‡∏á‡∏¢‡∏µ‡πà‡∏´‡πâ‡∏≠‡∏≠‡∏∞‡πÑ‡∏£" (‡πÄ‡∏ä‡πà‡∏ô Paracap)

  # üíä 3. ‡∏£‡∏∞‡∏ö‡∏ö‡∏´‡∏≤‡πÄ‡∏°‡πá‡∏î‡∏¢‡∏≤ (YOLO) - ‡πÉ‡∏ä‡πâ‡πÉ‡∏ô QC Mode / Pill Mode
  pill_detector:
    enabled: true
    onnx: "pill_detector.onnx" 
    conf_threshold: 0.6  # ‡∏Ñ‡∏ß‡∏≤‡∏°‡∏°‡∏±‡πà‡∏ô‡πÉ‡∏à‡∏ß‡πà‡∏≤ "‡πÄ‡∏à‡∏≠‡πÄ‡∏°‡πá‡∏î‡∏¢‡∏≤" (YOLO) - ‡∏õ‡∏Å‡∏ï‡∏¥‡πÄ‡∏°‡πá‡∏î‡πÄ‡∏•‡πá‡∏Å‡∏ï‡πâ‡∏≠‡∏á‡πÉ‡∏ä‡πâ‡∏Ñ‡πà‡∏≤‡∏ô‡πâ‡∏≠‡∏¢‡∏´‡∏ô‡πà‡∏≠‡∏¢

  # üß™ 4. ‡∏£‡∏∞‡∏ö‡∏ö‡∏≠‡πà‡∏≤‡∏ô‡∏ä‡∏∑‡πà‡∏≠‡∏¢‡∏≤ (ArcFace)
  pill_classifier:
    enabled: true
    weights: "pill_model_production.pth"
    img_size: 384
    conf_threshold: 0.9  # ‡∏Ñ‡∏ß‡∏≤‡∏°‡∏°‡∏±‡πà‡∏ô‡πÉ‡∏à‡∏ß‡πà‡∏≤ "‡πÄ‡∏õ‡πá‡∏ô‡∏¢‡∏≤‡∏≠‡∏∞‡πÑ‡∏£"